//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.h
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#ifndef __LH_SPRITES_EXT__
#define __LH_SPRITES_EXT__

#include "LevelHelperLoader.h"

class LHSpritesExt 
{
public:

    static std::string uniqueNameForBody(b2Body* body);
//------------------------------------------------------------------------------
    static bool isLHSprite(CCNode* obj);
    static bool isLHBezierNode(CCNode* obj);
//------------------------------------------------------------------------------
    //if fail will return -1
    static int  tagForBody(b2Body* body);
//------------------------------------------------------------------------------
    static LHSprite* spriteForBody(b2Body* body);
//------------------------------------------------------------------------------    
    static bool removeSpriteWithUniqueName(const std::string& name, LevelHelperLoader* loader);
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
    //the following methods will be removed in the near future
    static int  tagForSprite(CCNode* sprite);
    static std::string uniqueNameForSprite(LHSprite* sprite);    
    
    static bool removeBodyWithUniqueName(const std::string& name, LevelHelperLoader* loader);
    static bool removeBody(b2Body* body, LevelHelperLoader* loader);    
    static std::vector<b2Body*> bodiesWithTag(enum LevelHelper_TAG tag, LevelHelperLoader* loader);
};
#endif